export interface StockBasicLite {
  code: string;
  name: string;
  type: 'stock' | 'index';
  industry?: string;
}

export const STOCK_POOL_BUILTIN: StockBasicLite[] = [
  { code: 'sh.600519', name: '贵州茅台', type: 'stock', industry: '食品饮料' },
  { code: 'sz.000858', name: '五粮液', type: 'stock', industry: '食品饮料' },
  { code: 'sz.002594', name: '比亚迪', type: 'stock', industry: '汽车与新能源' },
  { code: 'sz.300750', name: '宁德时代', type: 'stock', industry: '汽车与新能源' },
  { code: 'sh.601318', name: '中国平安', type: 'stock', industry: '非银金融' },
  { code: 'sh.600036', name: '招商银行', type: 'stock', industry: '银行' },
  { code: 'sh.601899', name: '紫金矿业', type: 'stock', industry: '有色金属' },
  { code: 'sh.600900', name: '长江电力', type: 'stock', industry: '公用事业' },
  { code: 'sz.000333', name: '美的集团', type: 'stock', industry: '家用电器' },
  { code: 'sz.002415', name: '海康威视', type: 'stock', industry: '计算机' },
  { code: 'sh.601012', name: '隆基绿能', type: 'stock', industry: '电力设备与新能源' },
  { code: 'sh.688981', name: '中芯国际', type: 'stock', industry: '电子半导体' },
  { code: 'sz.002475', name: '立讯精密', type: 'stock', industry: '电子半导体' },
  { code: 'sh.603259', name: '药明康德', type: 'stock', industry: '医药生物' },
  { code: 'sz.300059', name: '东方财富', type: 'stock', industry: '非银金融' },
  { code: 'sh.600030', name: '中信证券', type: 'stock', industry: '非银金融' },
  { code: 'sz.000725', name: '京东方A', type: 'stock', industry: '电子半导体' },
  { code: 'sh.600276', name: '恒瑞医药', type: 'stock', industry: '医药生物' },
  { code: 'sh.688111', name: '金山办公', type: 'stock', industry: '计算机' },
  { code: 'sz.000001', name: '平安银行', type: 'stock', industry: '银行' },
  { code: 'sz.000002', name: '万科A', type: 'stock', industry: '房地产' },
  { code: 'sh.601166', name: '兴业银行', type: 'stock', industry: '银行' },
  { code: 'sh.600000', name: '浦发银行', type: 'stock', industry: '银行' },
  { code: 'sz.002142', name: '宁波银行', type: 'stock', industry: '银行' },
  { code: 'sh.601398', name: '工商银行', type: 'stock', industry: '银行' },
  { code: 'sh.601288', name: '农业银行', type: 'stock', industry: '银行' },
  { code: 'sh.601988', name: '中国银行', type: 'stock', industry: '银行' },
  { code: 'sh.601328', name: '交通银行', type: 'stock', industry: '银行' },
  { code: 'sh.600887', name: '伊利股份', type: 'stock', industry: '食品饮料' },
  { code: 'sz.300760', name: '迈瑞医疗', type: 'stock', industry: '医药生物' },
  { code: 'sh.600585', name: '海螺水泥', type: 'stock', industry: '建筑建材' },
  { code: 'sh.601668', name: '中国建筑', type: 'stock', industry: '建筑建材' },
  { code: 'sz.000651', name: '格力电器', type: 'stock', industry: '家用电器' },
  { code: 'sh.600690', name: '海尔智家', type: 'stock', industry: '家用电器' },
  { code: 'sz.300015', name: '爱尔眼科', type: 'stock', industry: '医药生物' },
  { code: 'sh.600031', name: '三一重工', type: 'stock', industry: '机械设备' },
  { code: 'sh.601888', name: '中国中免', type: 'stock', industry: '社会服务' },
  { code: 'sz.000568', name: '泸州老窖', type: 'stock', industry: '食品饮料' },
  { code: 'sz.000596', name: '古井贡酒', type: 'stock', industry: '食品饮料' },
  { code: 'sh.600809', name: '山西汾酒', type: 'stock', industry: '食品饮料' },
  { code: 'sh.600745', name: '闻泰科技', type: 'stock', industry: '电子半导体' },
  { code: 'sh.603501', name: '韦尔股份', type: 'stock', industry: '电子半导体' },
  { code: 'sz.002049', name: '紫光国微', type: 'stock', industry: '电子半导体' },
  { code: 'sh.688012', name: '中微公司', type: 'stock', industry: '电子半导体' },
  { code: 'sh.603986', name: '兆易创新', type: 'stock', industry: '电子半导体' },
  { code: 'sz.300308', name: '中际旭创', type: 'stock', industry: '通信' },
  { code: 'sh.601138', name: '工业富联', type: 'stock', industry: '电子半导体' },
  { code: 'sz.002371', name: '北方华创', type: 'stock', industry: '电子半导体' },
  { code: 'sz.002555', name: '三七互娱', type: 'stock', industry: '传媒' },
  { code: 'sz.300413', name: '芒果超媒', type: 'stock', industry: '传媒' },
  { code: 'sh.600941', name: '中国移动', type: 'stock', industry: '通信' },
  { code: 'sh.601728', name: '中国电信', type: 'stock', industry: '通信' },
  { code: 'sh.600050', name: '中国联通', type: 'stock', industry: '通信' },
  { code: 'sz.000063', name: '中兴通讯', type: 'stock', industry: '通信' },
  { code: 'sz.002812', name: '恩捷股份', type: 'stock', industry: '汽车与新能源' },
  { code: 'sz.300014', name: '亿纬锂能', type: 'stock', industry: '汽车与新能源' },
  { code: 'sh.600089', name: '特变电工', type: 'stock', industry: '电力设备与新能源' },
  { code: 'sz.002230', name: '科大讯飞', type: 'stock', industry: '计算机' },
  { code: 'sz.300496', name: '中科创达', type: 'stock', industry: '计算机' },
  { code: 'sh.688036', name: '传音控股', type: 'stock', industry: '电子半导体' },
  { code: 'sz.002236', name: '大华股份', type: 'stock', industry: '计算机' },
  { code: 'sh.600570', name: '恒生电子', type: 'stock', industry: '计算机' },
  { code: 'sz.002027', name: '分众传媒', type: 'stock', industry: '传媒' },
  { code: 'sh.601633', name: '长城汽车', type: 'stock', industry: '汽车与新能源' },
  { code: 'sz.000625', name: '长安汽车', type: 'stock', industry: '汽车与新能源' },
  { code: 'sh.600104', name: '上汽集团', type: 'stock', industry: '汽车与新能源' },
  { code: 'sh.601601', name: '中国太保', type: 'stock', industry: '非银金融' },
  { code: 'sh.601628', name: '中国人寿', type: 'stock', industry: '非银金融' },
  { code: 'sh.601088', name: '中国神华', type: 'stock', industry: '煤炭' },
  { code: 'sh.601857', name: '中国石油', type: 'stock', industry: '石油石化' },
  { code: 'sh.600028', name: '中国石化', type: 'stock', industry: '石油石化' },
  { code: 'sh.000001', name: '上证指数', type: 'index' },
  { code: 'sz.399001', name: '深证成指', type: 'index' },
  { code: 'sz.399006', name: '创业板指', type: 'index' },
  { code: 'sh.000300', name: '沪深300', type: 'index' },
  { code: 'sh.000688', name: '科创50', type: 'index' },
];
